version: "2"

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
      PORT: "3000"
      REQ_PORT: "3333"
      DB_PORT: "3334"
      BASE_URL: http://backend-redis
      DB_URL: http://backend-mongo
    depends_on:
      - redis
      - backend-mongo
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend-redis:
    build: ./backend/redis
    ports:
      - "3333:3333"
    environment:
      CHOKIDAR_USEPOLLING: true
      PORT: "3333"
      REDIS_URL: redis://redis
    restart: always
    depends_on:
      - redis
    volumes:
      - /app/node_modules
      - ./backend/redis:/app

  backend-mongo:
    build: ./backend/mongo
    ports:
      - "3334:3334"
    restart: always
    environment:
      PORT: "3334"
      URL_DB: mongodb://root:example@mongo:27017/
    volumes:
      - /app/node_modules
      - ./backend/mongo:/app
    depends_on:
      - mongo-express
      - mongo

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
